/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.k.shuffler.tables.Event;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRecord extends UpdatableRecordImpl<EventRecord> implements Record8<Long, Long, String, OffsetDateTime, OffsetDateTime, String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.event.id</code>.
     */
    public EventRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.event.chat_id</code>.
     */
    public EventRecord setChatId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.event.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.event.status</code>.
     */
    public EventRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.event.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.event.started_at</code>.
     */
    public EventRecord setStartedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.event.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.event.finished_at</code>.
     */
    public EventRecord setFinishedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.event.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.event.discipline</code>.
     */
    public EventRecord setDiscipline(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.event.discipline</code>.
     */
    public String getDiscipline() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.event.season_id</code>.
     */
    public EventRecord setSeasonId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.event.season_id</code>.
     */
    public Long getSeasonId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.event.index</code>.
     */
    public EventRecord setIndex(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.event.index</code>.
     */
    public Long getIndex() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, OffsetDateTime, OffsetDateTime, String, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, String, OffsetDateTime, OffsetDateTime, String, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Event.EVENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Event.EVENT.CHAT_ID;
    }

    @Override
    public Field<String> field3() {
        return Event.EVENT.STATUS;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Event.EVENT.STARTED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Event.EVENT.FINISHED_AT;
    }

    @Override
    public Field<String> field6() {
        return Event.EVENT.DISCIPLINE;
    }

    @Override
    public Field<Long> field7() {
        return Event.EVENT.SEASON_ID;
    }

    @Override
    public Field<Long> field8() {
        return Event.EVENT.INDEX;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getChatId();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public OffsetDateTime component4() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getFinishedAt();
    }

    @Override
    public String component6() {
        return getDiscipline();
    }

    @Override
    public Long component7() {
        return getSeasonId();
    }

    @Override
    public Long component8() {
        return getIndex();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getChatId();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public OffsetDateTime value4() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getFinishedAt();
    }

    @Override
    public String value6() {
        return getDiscipline();
    }

    @Override
    public Long value7() {
        return getSeasonId();
    }

    @Override
    public Long value8() {
        return getIndex();
    }

    @Override
    public EventRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EventRecord value2(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public EventRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public EventRecord value4(OffsetDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public EventRecord value5(OffsetDateTime value) {
        setFinishedAt(value);
        return this;
    }

    @Override
    public EventRecord value6(String value) {
        setDiscipline(value);
        return this;
    }

    @Override
    public EventRecord value7(Long value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public EventRecord value8(Long value) {
        setIndex(value);
        return this;
    }

    @Override
    public EventRecord values(Long value1, Long value2, String value3, OffsetDateTime value4, OffsetDateTime value5, String value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRecord
     */
    public EventRecord() {
        super(Event.EVENT);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(Long id, Long chatId, String status, OffsetDateTime startedAt, OffsetDateTime finishedAt, String discipline, Long seasonId, Long index) {
        super(Event.EVENT);

        setId(id);
        setChatId(chatId);
        setStatus(status);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
        setDiscipline(discipline);
        setSeasonId(seasonId);
        setIndex(index);
    }

    /**
     * Create a detached, initialised EventRecord
     */
    public EventRecord(ru.acuma.k.shuffler.tables.pojos.Event value) {
        super(Event.EVENT);

        if (value != null) {
            setId(value.getId());
            setChatId(value.getChatId());
            setStatus(value.getStatus());
            setStartedAt(value.getStartedAt());
            setFinishedAt(value.getFinishedAt());
            setDiscipline(value.getDiscipline());
            setSeasonId(value.getSeasonId());
            setIndex(value.getIndex());
        }
    }
}
