/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.k.shuffler.tables.Game;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record9<Long, Long, Integer, OffsetDateTime, OffsetDateTime, Long, Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.game.id</code>.
     */
    public GameRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.game.event_id</code>.
     */
    public GameRecord setEventId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.game.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.game.index</code>.
     */
    public GameRecord setIndex(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.game.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.game.started_at</code>.
     */
    public GameRecord setStartedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.game.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.game.finished_at</code>.
     */
    public GameRecord setFinishedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.game.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.game.winner_team_id</code>.
     */
    public GameRecord setWinnerTeamId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.game.winner_team_id</code>.
     */
    public Long getWinnerTeamId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.game.loser_team_id</code>.
     */
    public GameRecord setLoserTeamId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.game.loser_team_id</code>.
     */
    public Long getLoserTeamId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.game.discipline</code>.
     */
    public GameRecord setDiscipline(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.game.discipline</code>.
     */
    public String getDiscipline() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.game.season_id</code>.
     */
    public GameRecord setSeasonId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.game.season_id</code>.
     */
    public Long getSeasonId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Integer, OffsetDateTime, OffsetDateTime, Long, Long, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, Integer, OffsetDateTime, OffsetDateTime, Long, Long, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Game.GAME.ID;
    }

    @Override
    public Field<Long> field2() {
        return Game.GAME.EVENT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Game.GAME.INDEX;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Game.GAME.STARTED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Game.GAME.FINISHED_AT;
    }

    @Override
    public Field<Long> field6() {
        return Game.GAME.WINNER_TEAM_ID;
    }

    @Override
    public Field<Long> field7() {
        return Game.GAME.LOSER_TEAM_ID;
    }

    @Override
    public Field<String> field8() {
        return Game.GAME.DISCIPLINE;
    }

    @Override
    public Field<Long> field9() {
        return Game.GAME.SEASON_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getEventId();
    }

    @Override
    public Integer component3() {
        return getIndex();
    }

    @Override
    public OffsetDateTime component4() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getFinishedAt();
    }

    @Override
    public Long component6() {
        return getWinnerTeamId();
    }

    @Override
    public Long component7() {
        return getLoserTeamId();
    }

    @Override
    public String component8() {
        return getDiscipline();
    }

    @Override
    public Long component9() {
        return getSeasonId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getEventId();
    }

    @Override
    public Integer value3() {
        return getIndex();
    }

    @Override
    public OffsetDateTime value4() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getFinishedAt();
    }

    @Override
    public Long value6() {
        return getWinnerTeamId();
    }

    @Override
    public Long value7() {
        return getLoserTeamId();
    }

    @Override
    public String value8() {
        return getDiscipline();
    }

    @Override
    public Long value9() {
        return getSeasonId();
    }

    @Override
    public GameRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public GameRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public GameRecord value3(Integer value) {
        setIndex(value);
        return this;
    }

    @Override
    public GameRecord value4(OffsetDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public GameRecord value5(OffsetDateTime value) {
        setFinishedAt(value);
        return this;
    }

    @Override
    public GameRecord value6(Long value) {
        setWinnerTeamId(value);
        return this;
    }

    @Override
    public GameRecord value7(Long value) {
        setLoserTeamId(value);
        return this;
    }

    @Override
    public GameRecord value8(String value) {
        setDiscipline(value);
        return this;
    }

    @Override
    public GameRecord value9(Long value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public GameRecord values(Long value1, Long value2, Integer value3, OffsetDateTime value4, OffsetDateTime value5, Long value6, Long value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(Long id, Long eventId, Integer index, OffsetDateTime startedAt, OffsetDateTime finishedAt, Long winnerTeamId, Long loserTeamId, String discipline, Long seasonId) {
        super(Game.GAME);

        setId(id);
        setEventId(eventId);
        setIndex(index);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
        setWinnerTeamId(winnerTeamId);
        setLoserTeamId(loserTeamId);
        setDiscipline(discipline);
        setSeasonId(seasonId);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(ru.acuma.k.shuffler.tables.pojos.Game value) {
        super(Game.GAME);

        if (value != null) {
            setId(value.getId());
            setEventId(value.getEventId());
            setIndex(value.getIndex());
            setStartedAt(value.getStartedAt());
            setFinishedAt(value.getFinishedAt());
            setWinnerTeamId(value.getWinnerTeamId());
            setLoserTeamId(value.getLoserTeamId());
            setDiscipline(value.getDiscipline());
            setSeasonId(value.getSeasonId());
        }
    }
}
