/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.k.shuffler.tables.Player;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> implements Record6<Long, Long, Long, Integer, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.player.id</code>.
     */
    public PlayerRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.player.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.player.chat_id</code>.
     */
    public PlayerRecord setChatId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.player.chat_id</code>.
     */
    public Long getChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.player.user_id</code>.
     */
    public PlayerRecord setUserId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.player.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.player.rating</code>.
     */
    public PlayerRecord setRating(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.player.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.player.discipline</code>.
     */
    public PlayerRecord setDiscipline(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.player.discipline</code>.
     */
    public String getDiscipline() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.player.season_id</code>.
     */
    public PlayerRecord setSeasonId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.player.season_id</code>.
     */
    public Long getSeasonId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Integer, String, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Integer, String, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Player.PLAYER.ID;
    }

    @Override
    public Field<Long> field2() {
        return Player.PLAYER.CHAT_ID;
    }

    @Override
    public Field<Long> field3() {
        return Player.PLAYER.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Player.PLAYER.RATING;
    }

    @Override
    public Field<String> field5() {
        return Player.PLAYER.DISCIPLINE;
    }

    @Override
    public Field<Long> field6() {
        return Player.PLAYER.SEASON_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getChatId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getRating();
    }

    @Override
    public String component5() {
        return getDiscipline();
    }

    @Override
    public Long component6() {
        return getSeasonId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getChatId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getRating();
    }

    @Override
    public String value5() {
        return getDiscipline();
    }

    @Override
    public Long value6() {
        return getSeasonId();
    }

    @Override
    public PlayerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PlayerRecord value2(Long value) {
        setChatId(value);
        return this;
    }

    @Override
    public PlayerRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public PlayerRecord value4(Integer value) {
        setRating(value);
        return this;
    }

    @Override
    public PlayerRecord value5(String value) {
        setDiscipline(value);
        return this;
    }

    @Override
    public PlayerRecord value6(Long value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public PlayerRecord values(Long value1, Long value2, Long value3, Integer value4, String value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(Long id, Long chatId, Long userId, Integer rating, String discipline, Long seasonId) {
        super(Player.PLAYER);

        setId(id);
        setChatId(chatId);
        setUserId(userId);
        setRating(rating);
        setDiscipline(discipline);
        setSeasonId(seasonId);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(ru.acuma.k.shuffler.tables.pojos.Player value) {
        super(Player.PLAYER);

        if (value != null) {
            setId(value.getId());
            setChatId(value.getChatId());
            setUserId(value.getUserId());
            setRating(value.getRating());
            setDiscipline(value.getDiscipline());
            setSeasonId(value.getSeasonId());
        }
    }
}
