/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.acuma.shuffler.tables.Event;
import ru.acuma.shuffler.tables.FlywaySchemaHistory;
import ru.acuma.shuffler.tables.Game;
import ru.acuma.shuffler.tables.GroupInfo;
import ru.acuma.shuffler.tables.Player;
import ru.acuma.shuffler.tables.Rating;
import ru.acuma.shuffler.tables.RatingHistory;
import ru.acuma.shuffler.tables.Season;
import ru.acuma.shuffler.tables.Team;
import ru.acuma.shuffler.tables.TeamPlayer;
import ru.acuma.shuffler.tables.UserInfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.event</code>.
     */
    public final Event EVENT = Event.EVENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.game</code>.
     */
    public final Game GAME = Game.GAME;

    /**
     * The table <code>public.group_info</code>.
     */
    public final GroupInfo GROUP_INFO = GroupInfo.GROUP_INFO;

    /**
     * The table <code>public.player</code>.
     */
    public final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>public.rating</code>.
     */
    public final Rating RATING = Rating.RATING;

    /**
     * The table <code>public.rating_history</code>.
     */
    public final RatingHistory RATING_HISTORY = RatingHistory.RATING_HISTORY;

    /**
     * The table <code>public.season</code>.
     */
    public final Season SEASON = Season.SEASON;

    /**
     * The table <code>public.team</code>.
     */
    public final Team TEAM = Team.TEAM;

    /**
     * The table <code>public.team_player</code>.
     */
    public final TeamPlayer TEAM_PLAYER = TeamPlayer.TEAM_PLAYER;

    /**
     * The table <code>public.user_info</code>.
     */
    public final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Event.EVENT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Game.GAME,
            GroupInfo.GROUP_INFO,
            Player.PLAYER,
            Rating.RATING,
            RatingHistory.RATING_HISTORY,
            Season.SEASON,
            Team.TEAM,
            TeamPlayer.TEAM_PLAYER,
            UserInfo.USER_INFO
        );
    }
}
