/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler;


import ru.acuma.shuffler.tables.Event;
import ru.acuma.shuffler.tables.FlywaySchemaHistory;
import ru.acuma.shuffler.tables.Game;
import ru.acuma.shuffler.tables.GroupInfo;
import ru.acuma.shuffler.tables.Player;
import ru.acuma.shuffler.tables.Rating;
import ru.acuma.shuffler.tables.RatingHistory;
import ru.acuma.shuffler.tables.Season;
import ru.acuma.shuffler.tables.Team;
import ru.acuma.shuffler.tables.TeamPlayer;
import ru.acuma.shuffler.tables.UserInfo;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.event</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.game</code>.
     */
    public static final Game GAME = Game.GAME;

    /**
     * The table <code>public.group_info</code>.
     */
    public static final GroupInfo GROUP_INFO = GroupInfo.GROUP_INFO;

    /**
     * The table <code>public.player</code>.
     */
    public static final Player PLAYER = Player.PLAYER;

    /**
     * The table <code>public.rating</code>.
     */
    public static final Rating RATING = Rating.RATING;

    /**
     * The table <code>public.rating_history</code>.
     */
    public static final RatingHistory RATING_HISTORY = RatingHistory.RATING_HISTORY;

    /**
     * The table <code>public.season</code>.
     */
    public static final Season SEASON = Season.SEASON;

    /**
     * The table <code>public.team</code>.
     */
    public static final Team TEAM = Team.TEAM;

    /**
     * The table <code>public.team_player</code>.
     */
    public static final TeamPlayer TEAM_PLAYER = TeamPlayer.TEAM_PLAYER;

    /**
     * The table <code>public.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;
}
