/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    chatId;
    private String  title;
    private Boolean isBlocked;
    private String  name;

    public GroupInfo() {}

    public GroupInfo(GroupInfo value) {
        this.chatId = value.chatId;
        this.title = value.title;
        this.isBlocked = value.isBlocked;
        this.name = value.name;
    }

    public GroupInfo(
        Long    chatId,
        String  title,
        Boolean isBlocked,
        String  name
    ) {
        this.chatId = chatId;
        this.title = title;
        this.isBlocked = isBlocked;
        this.name = name;
    }

    /**
     * Getter for <code>public.group_info.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.group_info.chat_id</code>.
     */
    public GroupInfo setChatId(Long chatId) {
        this.chatId = chatId;
        return this;
    }

    /**
     * Getter for <code>public.group_info.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.group_info.title</code>.
     */
    public GroupInfo setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>public.group_info.is_blocked</code>.
     */
    public Boolean getIsBlocked() {
        return this.isBlocked;
    }

    /**
     * Setter for <code>public.group_info.is_blocked</code>.
     */
    public GroupInfo setIsBlocked(Boolean isBlocked) {
        this.isBlocked = isBlocked;
        return this;
    }

    /**
     * Getter for <code>public.group_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.group_info.name</code>.
     */
    public GroupInfo setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupInfo (");

        sb.append(chatId);
        sb.append(", ").append(title);
        sb.append(", ").append(isBlocked);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
