/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private String  title;
    private Boolean isActive;
    private String  name;
    private String  telegramName;

    public GroupInfo() {}

    public GroupInfo(GroupInfo value) {
        this.id = value.id;
        this.title = value.title;
        this.isActive = value.isActive;
        this.name = value.name;
        this.telegramName = value.telegramName;
    }

    public GroupInfo(
        Long    id,
        String  title,
        Boolean isActive,
        String  name,
        String  telegramName
    ) {
        this.id = id;
        this.title = title;
        this.isActive = isActive;
        this.name = name;
        this.telegramName = telegramName;
    }

    /**
     * Getter for <code>public.group_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.group_info.id</code>.
     */
    public GroupInfo setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.group_info.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.group_info.title</code>.
     */
    public GroupInfo setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>public.group_info.is_active</code>.
     */
    public Boolean getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>public.group_info.is_active</code>.
     */
    public GroupInfo setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    /**
     * Getter for <code>public.group_info.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.group_info.name</code>.
     */
    public GroupInfo setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.group_info.telegram_name</code>.
     */
    public String getTelegramName() {
        return this.telegramName;
    }

    /**
     * Setter for <code>public.group_info.telegram_name</code>.
     */
    public GroupInfo setTelegramName(String telegramName) {
        this.telegramName = telegramName;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupInfo (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(isActive);
        sb.append(", ").append(name);
        sb.append(", ").append(telegramName);

        sb.append(")");
        return sb.toString();
    }
}
