/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Long    gameId;
    private Long    playerId;
    private Integer change;

    public RatingHistory() {}

    public RatingHistory(RatingHistory value) {
        this.id = value.id;
        this.gameId = value.gameId;
        this.playerId = value.playerId;
        this.change = value.change;
    }

    public RatingHistory(
        Long    id,
        Long    gameId,
        Long    playerId,
        Integer change
    ) {
        this.id = id;
        this.gameId = gameId;
        this.playerId = playerId;
        this.change = change;
    }

    /**
     * Getter for <code>public.rating_history.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.rating_history.id</code>.
     */
    public RatingHistory setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.game_id</code>.
     */
    public Long getGameId() {
        return this.gameId;
    }

    /**
     * Setter for <code>public.rating_history.game_id</code>.
     */
    public RatingHistory setGameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.player_id</code>.
     */
    public Long getPlayerId() {
        return this.playerId;
    }

    /**
     * Setter for <code>public.rating_history.player_id</code>.
     */
    public RatingHistory setPlayerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.change</code>.
     */
    public Integer getChange() {
        return this.change;
    }

    /**
     * Setter for <code>public.rating_history.change</code>.
     */
    public RatingHistory setChange(Integer change) {
        this.change = change;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RatingHistory (");

        sb.append(id);
        sb.append(", ").append(gameId);
        sb.append(", ").append(playerId);
        sb.append(", ").append(change);

        sb.append(")");
        return sb.toString();
    }
}
