/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RatingHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long gameId;
    private Long playerId;
    private Integer change;
    private Integer score;
    private Long seasonId;
    private Boolean isCalibrated;
    private String discipline;

    public RatingHistory() {
    }

    public RatingHistory(RatingHistory value) {
        this.id = value.id;
        this.gameId = value.gameId;
        this.playerId = value.playerId;
        this.change = value.change;
        this.score = value.score;
        this.seasonId = value.seasonId;
        this.isCalibrated = value.isCalibrated;
        this.discipline = value.discipline;
    }

    public RatingHistory(
            Long id,
            Long gameId,
            Long playerId,
            Integer change,
            Integer score,
            Long seasonId,
            Boolean isCalibrated,
            String discipline
    ) {
        this.id = id;
        this.gameId = gameId;
        this.playerId = playerId;
        this.change = change;
        this.score = score;
        this.seasonId = seasonId;
        this.isCalibrated = isCalibrated;
        this.discipline = discipline;
    }

    /**
     * Getter for <code>public.rating_history.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.rating_history.id</code>.
     */
    public RatingHistory setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.game_id</code>.
     */
    public Long getGameId() {
        return this.gameId;
    }

    /**
     * Setter for <code>public.rating_history.game_id</code>.
     */
    public RatingHistory setGameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.player_id</code>.
     */
    public Long getPlayerId() {
        return this.playerId;
    }

    /**
     * Setter for <code>public.rating_history.player_id</code>.
     */
    public RatingHistory setPlayerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.change</code>.
     */
    public Integer getChange() {
        return this.change;
    }

    /**
     * Setter for <code>public.rating_history.change</code>.
     */
    public RatingHistory setChange(Integer change) {
        this.change = change;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.score</code>.
     */
    public Integer getScore() {
        return this.score;
    }

    /**
     * Setter for <code>public.rating_history.score</code>.
     */
    public RatingHistory setScore(Integer score) {
        this.score = score;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.season_id</code>.
     */
    public Long getSeasonId() {
        return this.seasonId;
    }

    /**
     * Setter for <code>public.rating_history.season_id</code>.
     */
    public RatingHistory setSeasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.is_calibrated</code>.
     */
    public Boolean getIsCalibrated() {
        return this.isCalibrated;
    }

    /**
     * Setter for <code>public.rating_history.is_calibrated</code>.
     */
    public RatingHistory setIsCalibrated(Boolean isCalibrated) {
        this.isCalibrated = isCalibrated;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.discipline</code>.
     */
    public String getDiscipline() {
        return this.discipline;
    }

    /**
     * Setter for <code>public.rating_history.discipline</code>.
     */
    public RatingHistory setDiscipline(String discipline) {
        this.discipline = discipline;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RatingHistory (");

        sb.append(id);
        sb.append(", ").append(gameId);
        sb.append(", ").append(playerId);
        sb.append(", ").append(change);
        sb.append(", ").append(score);
        sb.append(", ").append(seasonId);
        sb.append(", ").append(isCalibrated);
        sb.append(", ").append(discipline);

        sb.append(")");
        return sb.toString();
    }
}
