/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Season implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private OffsetDateTime startedAt;
    private OffsetDateTime finishedAt;
    private String         name;

    public Season() {}

    public Season(Season value) {
        this.id = value.id;
        this.startedAt = value.startedAt;
        this.finishedAt = value.finishedAt;
        this.name = value.name;
    }

    public Season(
        Long           id,
        OffsetDateTime startedAt,
        OffsetDateTime finishedAt,
        String         name
    ) {
        this.id = id;
        this.startedAt = startedAt;
        this.finishedAt = finishedAt;
        this.name = name;
    }

    /**
     * Getter for <code>public.season.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.season.id</code>.
     */
    public Season setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.season.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.season.started_at</code>.
     */
    public Season setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.season.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.season.finished_at</code>.
     */
    public Season setFinishedAt(OffsetDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    /**
     * Getter for <code>public.season.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.season.name</code>.
     */
    public Season setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Season (");

        sb.append(id);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(finishedAt);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
