/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private String         languageCode;
    private String         firstName;
    private String         lastName;
    private String         userName;
    private Boolean        isActive;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private OffsetDateTime deletedAt;
    private String         mediaId;

    public UserInfo() {}

    public UserInfo(UserInfo value) {
        this.id = value.id;
        this.languageCode = value.languageCode;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.userName = value.userName;
        this.isActive = value.isActive;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.deletedAt = value.deletedAt;
        this.mediaId = value.mediaId;
    }

    public UserInfo(
        Long           id,
        String         languageCode,
        String         firstName,
        String         lastName,
        String         userName,
        Boolean        isActive,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        OffsetDateTime deletedAt,
        String         mediaId
    ) {
        this.id = id;
        this.languageCode = languageCode;
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
        this.isActive = isActive;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.deletedAt = deletedAt;
        this.mediaId = mediaId;
    }

    /**
     * Getter for <code>public.user_info.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user_info.id</code>.
     */
    public UserInfo setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.user_info.language_code</code>.
     */
    public String getLanguageCode() {
        return this.languageCode;
    }

    /**
     * Setter for <code>public.user_info.language_code</code>.
     */
    public UserInfo setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
        return this;
    }

    /**
     * Getter for <code>public.user_info.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.user_info.first_name</code>.
     */
    public UserInfo setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>public.user_info.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.user_info.last_name</code>.
     */
    public UserInfo setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>public.user_info.user_name</code>.
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>public.user_info.user_name</code>.
     */
    public UserInfo setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>public.user_info.is_active</code>.
     */
    public Boolean getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>public.user_info.is_active</code>.
     */
    public UserInfo setIsActive(Boolean isActive) {
        this.isActive = isActive;
        return this;
    }

    /**
     * Getter for <code>public.user_info.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.user_info.created_at</code>.
     */
    public UserInfo setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.user_info.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.user_info.updated_at</code>.
     */
    public UserInfo setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Getter for <code>public.user_info.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return this.deletedAt;
    }

    /**
     * Setter for <code>public.user_info.deleted_at</code>.
     */
    public UserInfo setDeletedAt(OffsetDateTime deletedAt) {
        this.deletedAt = deletedAt;
        return this;
    }

    /**
     * Getter for <code>public.user_info.media_id</code>.
     */
    public String getMediaId() {
        return this.mediaId;
    }

    /**
     * Setter for <code>public.user_info.media_id</code>.
     */
    public UserInfo setMediaId(String mediaId) {
        this.mediaId = mediaId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserInfo (");

        sb.append(id);
        sb.append(", ").append(languageCode);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(userName);
        sb.append(", ").append(isActive);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(deletedAt);
        sb.append(", ").append(mediaId);

        sb.append(")");
        return sb.toString();
    }
}
