/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long           id;
    private Long           eventId;
    private Integer        index;
    private OffsetDateTime startedAt;
    private OffsetDateTime finishedAt;
    private Long           winnerTeamId;
    private Long           loserTeamId;
    private String         discipline;
    private Long           seasonId;

    public Game() {}

    public Game(Game value) {
        this.id = value.id;
        this.eventId = value.eventId;
        this.index = value.index;
        this.startedAt = value.startedAt;
        this.finishedAt = value.finishedAt;
        this.winnerTeamId = value.winnerTeamId;
        this.loserTeamId = value.loserTeamId;
        this.discipline = value.discipline;
        this.seasonId = value.seasonId;
    }

    public Game(
        Long           id,
        Long           eventId,
        Integer        index,
        OffsetDateTime startedAt,
        OffsetDateTime finishedAt,
        Long           winnerTeamId,
        Long           loserTeamId,
        String         discipline,
        Long           seasonId
    ) {
        this.id = id;
        this.eventId = eventId;
        this.index = index;
        this.startedAt = startedAt;
        this.finishedAt = finishedAt;
        this.winnerTeamId = winnerTeamId;
        this.loserTeamId = loserTeamId;
        this.discipline = discipline;
        this.seasonId = seasonId;
    }

    /**
     * Getter for <code>public.game.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.game.id</code>.
     */
    public Game setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.game.event_id</code>.
     */
    public Long getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>public.game.event_id</code>.
     */
    public Game setEventId(Long eventId) {
        this.eventId = eventId;
        return this;
    }

    /**
     * Getter for <code>public.game.index</code>.
     */
    public Integer getIndex() {
        return this.index;
    }

    /**
     * Setter for <code>public.game.index</code>.
     */
    public Game setIndex(Integer index) {
        this.index = index;
        return this;
    }

    /**
     * Getter for <code>public.game.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>public.game.started_at</code>.
     */
    public Game setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>public.game.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.game.finished_at</code>.
     */
    public Game setFinishedAt(OffsetDateTime finishedAt) {
        this.finishedAt = finishedAt;
        return this;
    }

    /**
     * Getter for <code>public.game.winner_team_id</code>.
     */
    public Long getWinnerTeamId() {
        return this.winnerTeamId;
    }

    /**
     * Setter for <code>public.game.winner_team_id</code>.
     */
    public Game setWinnerTeamId(Long winnerTeamId) {
        this.winnerTeamId = winnerTeamId;
        return this;
    }

    /**
     * Getter for <code>public.game.loser_team_id</code>.
     */
    public Long getLoserTeamId() {
        return this.loserTeamId;
    }

    /**
     * Setter for <code>public.game.loser_team_id</code>.
     */
    public Game setLoserTeamId(Long loserTeamId) {
        this.loserTeamId = loserTeamId;
        return this;
    }

    /**
     * Getter for <code>public.game.discipline</code>.
     */
    public String getDiscipline() {
        return this.discipline;
    }

    /**
     * Setter for <code>public.game.discipline</code>.
     */
    public Game setDiscipline(String discipline) {
        this.discipline = discipline;
        return this;
    }

    /**
     * Getter for <code>public.game.season_id</code>.
     */
    public Long getSeasonId() {
        return this.seasonId;
    }

    /**
     * Setter for <code>public.game.season_id</code>.
     */
    public Game setSeasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Game (");

        sb.append(id);
        sb.append(", ").append(eventId);
        sb.append(", ").append(index);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(finishedAt);
        sb.append(", ").append(winnerTeamId);
        sb.append(", ").append(loserTeamId);
        sb.append(", ").append(discipline);
        sb.append(", ").append(seasonId);

        sb.append(")");
        return sb.toString();
    }
}
