/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Player implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Long    chatId;
    private Long    userId;
    private Integer rating;
    private String  discipline;
    private Long    seasonId;
    private Long    firstPlayerId;
    private Long    secondPlayerId;

    public Player() {}

    public Player(Player value) {
        this.id = value.id;
        this.chatId = value.chatId;
        this.userId = value.userId;
        this.rating = value.rating;
        this.discipline = value.discipline;
        this.seasonId = value.seasonId;
        this.firstPlayerId = value.firstPlayerId;
        this.secondPlayerId = value.secondPlayerId;
    }

    public Player(
        Long    id,
        Long    chatId,
        Long    userId,
        Integer rating,
        String  discipline,
        Long    seasonId,
        Long    firstPlayerId,
        Long    secondPlayerId
    ) {
        this.id = id;
        this.chatId = chatId;
        this.userId = userId;
        this.rating = rating;
        this.discipline = discipline;
        this.seasonId = seasonId;
        this.firstPlayerId = firstPlayerId;
        this.secondPlayerId = secondPlayerId;
    }

    /**
     * Getter for <code>public.player.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.player.id</code>.
     */
    public Player setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.player.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.player.chat_id</code>.
     */
    public Player setChatId(Long chatId) {
        this.chatId = chatId;
        return this;
    }

    /**
     * Getter for <code>public.player.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.player.user_id</code>.
     */
    public Player setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.player.rating</code>.
     */
    public Integer getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>public.player.rating</code>.
     */
    public Player setRating(Integer rating) {
        this.rating = rating;
        return this;
    }

    /**
     * Getter for <code>public.player.discipline</code>.
     */
    public String getDiscipline() {
        return this.discipline;
    }

    /**
     * Setter for <code>public.player.discipline</code>.
     */
    public Player setDiscipline(String discipline) {
        this.discipline = discipline;
        return this;
    }

    /**
     * Getter for <code>public.player.season_id</code>.
     */
    public Long getSeasonId() {
        return this.seasonId;
    }

    /**
     * Setter for <code>public.player.season_id</code>.
     */
    public Player setSeasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    /**
     * Getter for <code>public.player.first_player_id</code>.
     */
    public Long getFirstPlayerId() {
        return this.firstPlayerId;
    }

    /**
     * Setter for <code>public.player.first_player_id</code>.
     */
    public Player setFirstPlayerId(Long firstPlayerId) {
        this.firstPlayerId = firstPlayerId;
        return this;
    }

    /**
     * Getter for <code>public.player.second_player_id</code>.
     */
    public Long getSecondPlayerId() {
        return this.secondPlayerId;
    }

    /**
     * Setter for <code>public.player.second_player_id</code>.
     */
    public Player setSecondPlayerId(Long secondPlayerId) {
        this.secondPlayerId = secondPlayerId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Player (");

        sb.append(id);
        sb.append(", ").append(chatId);
        sb.append(", ").append(userId);
        sb.append(", ").append(rating);
        sb.append(", ").append(discipline);
        sb.append(", ").append(seasonId);
        sb.append(", ").append(firstPlayerId);
        sb.append(", ").append(secondPlayerId);

        sb.append(")");
        return sb.toString();
    }
}
