/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Long    playerId;
    private Long    gameId;
    private Long    seasonId;
    private String  discipline;
    private Integer change;
    private Long    chatId;

    public RatingHistory() {}

    public RatingHistory(RatingHistory value) {
        this.id = value.id;
        this.playerId = value.playerId;
        this.gameId = value.gameId;
        this.seasonId = value.seasonId;
        this.discipline = value.discipline;
        this.change = value.change;
        this.chatId = value.chatId;
    }

    public RatingHistory(
        Long    id,
        Long    playerId,
        Long    gameId,
        Long    seasonId,
        String  discipline,
        Integer change,
        Long    chatId
    ) {
        this.id = id;
        this.playerId = playerId;
        this.gameId = gameId;
        this.seasonId = seasonId;
        this.discipline = discipline;
        this.change = change;
        this.chatId = chatId;
    }

    /**
     * Getter for <code>public.rating_history.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.rating_history.id</code>.
     */
    public RatingHistory setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.player_id</code>.
     */
    public Long getPlayerId() {
        return this.playerId;
    }

    /**
     * Setter for <code>public.rating_history.player_id</code>.
     */
    public RatingHistory setPlayerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.game_id</code>.
     */
    public Long getGameId() {
        return this.gameId;
    }

    /**
     * Setter for <code>public.rating_history.game_id</code>.
     */
    public RatingHistory setGameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.season_id</code>.
     */
    public Long getSeasonId() {
        return this.seasonId;
    }

    /**
     * Setter for <code>public.rating_history.season_id</code>.
     */
    public RatingHistory setSeasonId(Long seasonId) {
        this.seasonId = seasonId;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.discipline</code>.
     */
    public String getDiscipline() {
        return this.discipline;
    }

    /**
     * Setter for <code>public.rating_history.discipline</code>.
     */
    public RatingHistory setDiscipline(String discipline) {
        this.discipline = discipline;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.change</code>.
     */
    public Integer getChange() {
        return this.change;
    }

    /**
     * Setter for <code>public.rating_history.change</code>.
     */
    public RatingHistory setChange(Integer change) {
        this.change = change;
        return this;
    }

    /**
     * Getter for <code>public.rating_history.chat_id</code>.
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>public.rating_history.chat_id</code>.
     */
    public RatingHistory setChatId(Long chatId) {
        this.chatId = chatId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RatingHistory (");

        sb.append(id);
        sb.append(", ").append(playerId);
        sb.append(", ").append(gameId);
        sb.append(", ").append(seasonId);
        sb.append(", ").append(discipline);
        sb.append(", ").append(change);
        sb.append(", ").append(chatId);

        sb.append(")");
        return sb.toString();
    }
}
