/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamPlayer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long playerId;
    private Long teamId;

    public TeamPlayer() {}

    public TeamPlayer(TeamPlayer value) {
        this.id = value.id;
        this.playerId = value.playerId;
        this.teamId = value.teamId;
    }

    public TeamPlayer(
        Long id,
        Long playerId,
        Long teamId
    ) {
        this.id = id;
        this.playerId = playerId;
        this.teamId = teamId;
    }

    /**
     * Getter for <code>public.team_player.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.team_player.id</code>.
     */
    public TeamPlayer setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.team_player.player_id</code>.
     */
    public Long getPlayerId() {
        return this.playerId;
    }

    /**
     * Setter for <code>public.team_player.player_id</code>.
     */
    public TeamPlayer setPlayerId(Long playerId) {
        this.playerId = playerId;
        return this;
    }

    /**
     * Getter for <code>public.team_player.team_id</code>.
     */
    public Long getTeamId() {
        return this.teamId;
    }

    /**
     * Setter for <code>public.team_player.team_id</code>.
     */
    public TeamPlayer setTeamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TeamPlayer (");

        sb.append(id);
        sb.append(", ").append(playerId);
        sb.append(", ").append(teamId);

        sb.append(")");
        return sb.toString();
    }
}
