/*
 * This file is generated by jOOQ.
 */
package ru.acuma.k.shuffler.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Team implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Long    gameId;
    private Boolean winner;

    public Team() {}

    public Team(Team value) {
        this.id = value.id;
        this.gameId = value.gameId;
        this.winner = value.winner;
    }

    public Team(
        Long    id,
        Long    gameId,
        Boolean winner
    ) {
        this.id = id;
        this.gameId = gameId;
        this.winner = winner;
    }

    /**
     * Getter for <code>public.team.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.team.id</code>.
     */
    public Team setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.team.game_id</code>.
     */
    public Long getGameId() {
        return this.gameId;
    }

    /**
     * Setter for <code>public.team.game_id</code>.
     */
    public Team setGameId(Long gameId) {
        this.gameId = gameId;
        return this;
    }

    /**
     * Getter for <code>public.team.winner</code>.
     */
    public Boolean getWinner() {
        return this.winner;
    }

    /**
     * Setter for <code>public.team.winner</code>.
     */
    public Team setWinner(Boolean winner) {
        this.winner = winner;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Team (");

        sb.append(id);
        sb.append(", ").append(gameId);
        sb.append(", ").append(winner);

        sb.append(")");
        return sb.toString();
    }
}
