/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.shuffler.tables.Rating;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingRecord extends UpdatableRecordImpl<RatingRecord> implements Record6<Long, Long, Long, String, Integer, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rating.id</code>.
     */
    public RatingRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.rating.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.rating.player_id</code>.
     */
    public RatingRecord setPlayerId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.rating.player_id</code>.
     */
    public Long getPlayerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.rating.season_id</code>.
     */
    public RatingRecord setSeasonId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.rating.season_id</code>.
     */
    public Long getSeasonId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.rating.discipline</code>.
     */
    public RatingRecord setDiscipline(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.rating.discipline</code>.
     */
    public String getDiscipline() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.rating.score</code>.
     */
    public RatingRecord setScore(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.rating.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.rating.multiplier</code>.
     */
    public RatingRecord setMultiplier(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.rating.multiplier</code>.
     */
    public BigDecimal getMultiplier() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, String, Integer, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, String, Integer, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Rating.RATING.ID;
    }

    @Override
    public Field<Long> field2() {
        return Rating.RATING.PLAYER_ID;
    }

    @Override
    public Field<Long> field3() {
        return Rating.RATING.SEASON_ID;
    }

    @Override
    public Field<String> field4() {
        return Rating.RATING.DISCIPLINE;
    }

    @Override
    public Field<Integer> field5() {
        return Rating.RATING.SCORE;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Rating.RATING.MULTIPLIER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPlayerId();
    }

    @Override
    public Long component3() {
        return getSeasonId();
    }

    @Override
    public String component4() {
        return getDiscipline();
    }

    @Override
    public Integer component5() {
        return getScore();
    }

    @Override
    public BigDecimal component6() {
        return getMultiplier();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPlayerId();
    }

    @Override
    public Long value3() {
        return getSeasonId();
    }

    @Override
    public String value4() {
        return getDiscipline();
    }

    @Override
    public Integer value5() {
        return getScore();
    }

    @Override
    public BigDecimal value6() {
        return getMultiplier();
    }

    @Override
    public RatingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RatingRecord value2(Long value) {
        setPlayerId(value);
        return this;
    }

    @Override
    public RatingRecord value3(Long value) {
        setSeasonId(value);
        return this;
    }

    @Override
    public RatingRecord value4(String value) {
        setDiscipline(value);
        return this;
    }

    @Override
    public RatingRecord value5(Integer value) {
        setScore(value);
        return this;
    }

    @Override
    public RatingRecord value6(BigDecimal value) {
        setMultiplier(value);
        return this;
    }

    @Override
    public RatingRecord values(Long value1, Long value2, Long value3, String value4, Integer value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RatingRecord
     */
    public RatingRecord() {
        super(Rating.RATING);
    }

    /**
     * Create a detached, initialised RatingRecord
     */
    public RatingRecord(Long id, Long playerId, Long seasonId, String discipline, Integer score, BigDecimal multiplier) {
        super(Rating.RATING);

        setId(id);
        setPlayerId(playerId);
        setSeasonId(seasonId);
        setDiscipline(discipline);
        setScore(score);
        setMultiplier(multiplier);
    }

    /**
     * Create a detached, initialised RatingRecord
     */
    public RatingRecord(ru.acuma.shuffler.tables.pojos.Rating value) {
        super(Rating.RATING);

        if (value != null) {
            setId(value.getId());
            setPlayerId(value.getPlayerId());
            setSeasonId(value.getSeasonId());
            setDiscipline(value.getDiscipline());
            setScore(value.getScore());
            setMultiplier(value.getMultiplier());
        }
    }
}
