/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.shuffler.tables.RatingHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingHistoryRecord extends UpdatableRecordImpl<RatingHistoryRecord> implements Record5<Long, Long, Long, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.rating_history.id</code>.
     */
    public RatingHistoryRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.rating_history.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.rating_history.event_id</code>.
     */
    public RatingHistoryRecord setEventId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.rating_history.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.rating_history.game_id</code>.
     */
    public RatingHistoryRecord setGameId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.rating_history.game_id</code>.
     */
    public Long getGameId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.rating_history.player_id</code>.
     */
    public RatingHistoryRecord setPlayerId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.rating_history.player_id</code>.
     */
    public Long getPlayerId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.rating_history.change</code>.
     */
    public RatingHistoryRecord setChange(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.rating_history.change</code>.
     */
    public Integer getChange() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, Long, Long, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, Long, Long, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RatingHistory.RATING_HISTORY.ID;
    }

    @Override
    public Field<Long> field2() {
        return RatingHistory.RATING_HISTORY.EVENT_ID;
    }

    @Override
    public Field<Long> field3() {
        return RatingHistory.RATING_HISTORY.GAME_ID;
    }

    @Override
    public Field<Long> field4() {
        return RatingHistory.RATING_HISTORY.PLAYER_ID;
    }

    @Override
    public Field<Integer> field5() {
        return RatingHistory.RATING_HISTORY.CHANGE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getEventId();
    }

    @Override
    public Long component3() {
        return getGameId();
    }

    @Override
    public Long component4() {
        return getPlayerId();
    }

    @Override
    public Integer component5() {
        return getChange();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getEventId();
    }

    @Override
    public Long value3() {
        return getGameId();
    }

    @Override
    public Long value4() {
        return getPlayerId();
    }

    @Override
    public Integer value5() {
        return getChange();
    }

    @Override
    public RatingHistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RatingHistoryRecord value2(Long value) {
        setEventId(value);
        return this;
    }

    @Override
    public RatingHistoryRecord value3(Long value) {
        setGameId(value);
        return this;
    }

    @Override
    public RatingHistoryRecord value4(Long value) {
        setPlayerId(value);
        return this;
    }

    @Override
    public RatingHistoryRecord value5(Integer value) {
        setChange(value);
        return this;
    }

    @Override
    public RatingHistoryRecord values(Long value1, Long value2, Long value3, Long value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RatingHistoryRecord
     */
    public RatingHistoryRecord() {
        super(RatingHistory.RATING_HISTORY);
    }

    /**
     * Create a detached, initialised RatingHistoryRecord
     */
    public RatingHistoryRecord(Long id, Long eventId, Long gameId, Long playerId, Integer change) {
        super(RatingHistory.RATING_HISTORY);

        setId(id);
        setEventId(eventId);
        setGameId(gameId);
        setPlayerId(playerId);
        setChange(change);
    }

    /**
     * Create a detached, initialised RatingHistoryRecord
     */
    public RatingHistoryRecord(ru.acuma.shuffler.tables.pojos.RatingHistory value) {
        super(RatingHistory.RATING_HISTORY);

        if (value != null) {
            setId(value.getId());
            setEventId(value.getEventId());
            setGameId(value.getGameId());
            setPlayerId(value.getPlayerId());
            setChange(value.getChange());
        }
    }
}
