/*
 * This file is generated by jOOQ.
 */
package ru.acuma.shuffler.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import ru.acuma.shuffler.tables.UserInfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record10<Long, String, String, String, String, Boolean, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_info.id</code>.
     */
    public UserInfoRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_info.language_code</code>.
     */
    public UserInfoRecord setLanguageCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.language_code</code>.
     */
    public String getLanguageCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_info.first_name</code>.
     */
    public UserInfoRecord setFirstName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_info.last_name</code>.
     */
    public UserInfoRecord setLastName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_info.user_name</code>.
     */
    public UserInfoRecord setUserName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.user_name</code>.
     */
    public String getUserName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_info.is_active</code>.
     */
    public UserInfoRecord setIsActive(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.user_info.created_at</code>.
     */
    public UserInfoRecord setCreatedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.user_info.updated_at</code>.
     */
    public UserInfoRecord setUpdatedAt(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.user_info.deleted_at</code>.
     */
    public UserInfoRecord setDeletedAt(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.user_info.media_id</code>.
     */
    public UserInfoRecord setMediaId(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.user_info.media_id</code>.
     */
    public String getMediaId() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, String, String, String, Boolean, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, String, String, String, Boolean, OffsetDateTime, OffsetDateTime, OffsetDateTime, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserInfo.USER_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return UserInfo.USER_INFO.LANGUAGE_CODE;
    }

    @Override
    public Field<String> field3() {
        return UserInfo.USER_INFO.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return UserInfo.USER_INFO.LAST_NAME;
    }

    @Override
    public Field<String> field5() {
        return UserInfo.USER_INFO.USER_NAME;
    }

    @Override
    public Field<Boolean> field6() {
        return UserInfo.USER_INFO.IS_ACTIVE;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return UserInfo.USER_INFO.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return UserInfo.USER_INFO.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return UserInfo.USER_INFO.DELETED_AT;
    }

    @Override
    public Field<String> field10() {
        return UserInfo.USER_INFO.MEDIA_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLanguageCode();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public String component5() {
        return getUserName();
    }

    @Override
    public Boolean component6() {
        return getIsActive();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component9() {
        return getDeletedAt();
    }

    @Override
    public String component10() {
        return getMediaId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLanguageCode();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public String value5() {
        return getUserName();
    }

    @Override
    public Boolean value6() {
        return getIsActive();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value9() {
        return getDeletedAt();
    }

    @Override
    public String value10() {
        return getMediaId();
    }

    @Override
    public UserInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserInfoRecord value2(String value) {
        setLanguageCode(value);
        return this;
    }

    @Override
    public UserInfoRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserInfoRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserInfoRecord value5(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UserInfoRecord value6(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public UserInfoRecord value7(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserInfoRecord value8(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UserInfoRecord value9(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public UserInfoRecord value10(String value) {
        setMediaId(value);
        return this;
    }

    @Override
    public UserInfoRecord values(Long value1, String value2, String value3, String value4, String value5, Boolean value6, OffsetDateTime value7, OffsetDateTime value8, OffsetDateTime value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(Long id, String languageCode, String firstName, String lastName, String userName, Boolean isActive, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt, String mediaId) {
        super(UserInfo.USER_INFO);

        setId(id);
        setLanguageCode(languageCode);
        setFirstName(firstName);
        setLastName(lastName);
        setUserName(userName);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setMediaId(mediaId);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(ru.acuma.shuffler.tables.pojos.UserInfo value) {
        super(UserInfo.USER_INFO);

        if (value != null) {
            setId(value.getId());
            setLanguageCode(value.getLanguageCode());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setUserName(value.getUserName());
            setIsActive(value.getIsActive());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setDeletedAt(value.getDeletedAt());
            setMediaId(value.getMediaId());
        }
    }
}
